name = input("Enter Student Name: ")
roll = input("Enter Roll Number: ")
age = int(input("Enter Age: "))
course = input("Enter Course: ")

print("\n----- Student Information -----")
print("Name :", name)
print("Roll No :", roll)
print("Age :", age)
print("Course :", course)